site_name: omeROcrate
docs_dir: .
site_dir: ../site
exclude_docs: |
  test

plugins:
  - search
  - same-dir
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            separate_signature: false
            show_signature_annotations: false
            show_signature: true
  - redirects:
      redirect_maps:
        # Ensure all IRIs resolve to the IRI documentation page
        'segmentationFor.md': 'docs/iris.md'
        'upload.md': 'docs/iris.md'
        'experimenterGroup.md': 'docs/iris.md'


theme:
  name: material

markdown_extensions:
  - mkdocs-typer
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - Getting Started: README.md
  - docs/api.md
  - docs/cli.md
  - docs/iris.md
  - GitHub: 'https://github.com/WEHI-SODA-Hub/OmeroCrate'
